version: '3'
services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '5000:80'
  message-board-service:
    build:
      dockerfile: Dockerfile.dev
      context: ./message-board-service
    environment:
      - PGUSER=message_board
      - PGPASSWORD=Qwertyui1
      - PGURL=jdbc:postgresql://message-board-1.cvdwqjgyzhlh.us-east-1.rds.amazonaws.com:5432/postgres
  message-board-ui:
    build:
      dockerfile: Dockerfile.dev
      context: ./message-board-ui
    stdin_open: true